name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: clone web repository
        env:
          VITE_API_GATEWAY: ${{ secrets.VITE_API_GATEWAY }}
        run: |
          git clone https://github.com/maxischmaxi/league-game-web web
          cd web
          npm install
          npm run build
          cp -r dist ../public

      - name: install Railway
        run: npm i -g @railway/cli

      - name: deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up
          
